AllCops:
  DisplayCopNames: true

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Metrics/LineLength:
  Max: 100
Style/LineEndConcatenation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
